/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.*;
import helper.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import model.*;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;


/**
 *
 * @author MSI-VN
 */
public class DatVePanel extends javax.swing.JPanel {
    private mainform parentForm;  
    private DefaultTableModel tblModel;
    /**
     * Creates new form DatVePanel
     */
    public DatVePanel() {
        initComponents();
        
        initTable();
        
       loadDataToTable();
       LoadTuyenToCombobox();
       txtMatuyen.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel6 = new javax.swing.JLabel();
            cbxMaTuyen = new javax.swing.JComboBox<>();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblChuyenXe = new javax.swing.JTable();
            jTextField1 = new javax.swing.JTextField();
            txtMaGhe = new javax.swing.JTextField();
            txtSdt = new javax.swing.JTextField();
            txtHoten = new javax.swing.JTextField();
            txtNgaySinh = new javax.swing.JTextField();
            txtNgaydi = new javax.swing.JTextField();
            txtNgaydat = new javax.swing.JTextField();
            txtNhanVien = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            txtThanhTien = new javax.swing.JTextField();
            txtGiodi = new javax.swing.JTextField();
            jLabel13 = new javax.swing.JLabel();
            btnTim = new javax.swing.JButton();
            jLabel14 = new javax.swing.JLabel();
            txtMatuyen = new javax.swing.JTextField();
            btnDatVe = new javax.swing.JButton();
            jLabel7 = new javax.swing.JLabel();
            txtMaChuyen = new javax.swing.JTextField();
            txtMaKh = new javax.swing.JTextField();
            jLabel11 = new javax.swing.JLabel();
            lblCountGhe = new javax.swing.JLabel();
            btnLamMoi = new javax.swing.JButton();

            jLabel6.setText("Chọn Tuyến đường");

            cbxMaTuyen.addItemListener(new java.awt.event.ItemListener() {
                  public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        cbxMaTuyenItemStateChanged(evt);
                  }
            });

            tblChuyenXe.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                  }
            ));
            tblChuyenXe.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tblChuyenXeMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(tblChuyenXe);

            jTextField1.setEnabled(false);
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField1ActionPerformed(evt);
                  }
            });

            txtMaGhe.setEnabled(false);

            txtSdt.addCaretListener(new javax.swing.event.CaretListener() {
                  public void caretUpdate(javax.swing.event.CaretEvent evt) {
                        txtSdtCaretUpdate(evt);
                  }
            });
            txtSdt.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txtSdtKeyReleased(evt);
                  }
            });

            txtNhanVien.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtNhanVienActionPerformed(evt);
                  }
            });

            jLabel1.setText("Mã vé");

            jLabel2.setText("Mã ghế");

            jLabel3.setText("SĐT");

            jLabel4.setText("Họ tên");

            jLabel5.setText("Ngày sinh");

            jLabel8.setText("Ngày đi");

            jLabel9.setText("Ngày đặt vé");

            jLabel10.setText("NV bán vé");

            jLabel12.setText("Thành tiền");

            jLabel13.setText("Giờ đi");

            btnTim.setText("Tìm");
            btnTim.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnTimActionPerformed(evt);
                  }
            });

            jLabel14.setText("Mã tuyến");

            txtMatuyen.addCaretListener(new javax.swing.event.CaretListener() {
                  public void caretUpdate(javax.swing.event.CaretEvent evt) {
                        txtMatuyenCaretUpdate(evt);
                  }
            });
            txtMatuyen.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txtMatuyenKeyReleased(evt);
                  }
            });

            btnDatVe.setText("Đặt Vé");
            btnDatVe.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnDatVeActionPerformed(evt);
                  }
            });

            jLabel7.setText("Mã chuyến");

            jLabel11.setText("Mã KH");

            lblCountGhe.setText("jLabel15");

            btnLamMoi.setText("Làm mới");
            btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnLamMoiActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel6)
                                          .addComponent(btnTim)
                                          .addComponent(cbxMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(120, 120, 120)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(btnLamMoi)
                                    .addGap(235, 235, 235)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jLabel2)
                                                      .addComponent(jLabel3)
                                                      .addComponent(jLabel1)
                                                      .addComponent(jLabel4))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtMaGhe, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                                            .addComponent(txtSdt)
                                                            .addComponent(txtHoten)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                  .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtMatuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                  .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel7)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                              .addComponent(lblCountGhe)
                                                                              .addComponent(txtMaChuyen))))
                                                            .addGap(45, 45, 45)
                                                            .addComponent(btnDatVe))
                                                      .addComponent(jLabel11)
                                                      .addGroup(layout.createSequentialGroup()
                                                            .addGap(51, 51, 51)
                                                            .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                          .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                      .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(txtNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                                      .addComponent(txtNgaydat))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                      .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txtNgaydi))
                                                      .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addGap(22, 22, 22)
                                                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtGiodi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(20, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnTim))
                              .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel14)
                                                            .addComponent(txtMatuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnDatVe)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(txtMaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(txtMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                            .addGap(6, 6, 6)
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                      .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                            .addGap(6, 6, 6)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                      .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                            .addGap(6, 6, 6)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                      .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18))
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCountGhe)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                      .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel11))
                                                .addGap(67, 67, 67)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(txtNgaydi)
                                          .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(jLabel13)
                                          .addComponent(txtGiodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(txtNgaydat)
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnLamMoi)
                                    .addGap(6, 6, 6)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNhanVien)
                                    .addComponent(jLabel12)
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))
            );
      }// </editor-fold>//GEN-END:initComponents
    public void LoadTuyenToCombobox(){
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost;databaseName=QLVEXE;user=sa;password=123";
        Connection con = DriverManager.getConnection(connectionUrl);
        String sql ="select TenTuyen from TuyenXe";
        Statement st =con.createStatement();
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            cbxMaTuyen.removeAllItems();
            while (rs.next()){
                cbxMaTuyen.addItem(rs.getString("TenTuyen"));
                cbxMaTuyen.setSelectedItem("");
            }
            rs.close();
            pstmt.close();
            con.close();
        }catch(Exception e)
        {
            e.getStackTrace();
        }
     }
    
    private void initTable(){
       
      
    }
     int soluongghe = 0;
     String masoghe;
     
     public void ResetData(){
        txtNgaydi.setText("");
        txtGiodi.setText("");
        txtMaChuyen.setText("");
        txtMatuyen.setText("");
        txtNhanVien.setText("");  
        txtHoten.setText("");  
        txtThanhTien.setText(""); 
        txtMaKh.setText(""); 
        txtSdt.setText(""); 
        txtNgaySinh.setText(""); 
        txtNgaydat.setText(""); 
     } 
    public void loadDataToTable(){     
        try{
//            tblModel = new DefaultTableModel();
            tblModel = (DefaultTableModel) tblChuyenXe.getModel();
            tblModel.setColumnIdentifiers(new String[]{"Mã chuyến", "Mã tuyến","Ngày đi", "Giờ đi", "Giá vé","Trạng Thái"});
            tblChuyenXe.setModel(tblModel);
            
            ChuyenXeDao dao = new ChuyenXeDao();
            List<ChuyenXe> list = dao.findAll();
            tblModel.setRowCount(0);
            
            for(ChuyenXe it : list){            
                tblModel.addRow(new Object[]{
                it.getMaChuyen(), it.getMaTuyen(), it.getNgayDi(), it.getGioDi(), it.getGiaVe(), it.getTrangThai()
            });
            }            
            tblModel.fireTableDataChanged();

        } catch(Exception e)
        {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Loi");
        }
    }
    int quenry=0;
    public void curTime(){
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDateTime now = LocalDateTime.now();
            txtNgaydat.setText(dtf.format(now));
    }
     public void filter(){
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(tblModel);
//        tblChuyenXe.setRowSorter(tr);       
//        tr.setRowFilter(RowFilter.regexFilter(String.valueOf(a)));
    
        ChuyenXeDao dao = new ChuyenXeDao();
        DefaultTableModel  tblModel2 = (DefaultTableModel) tblChuyenXe.getModel();
        tblModel2.setRowCount(0);
        
        for (ChuyenXe s : dao.findBuyName(quenry)){
            Object dataRow[] = new Object[6];
            dataRow[0] = s.getMaChuyen();
            dataRow[1] = s.getMaTuyen();
            dataRow[2] = s.getNgayDi();
            dataRow[3] = s.getGioDi();
            dataRow[4] = s.getGiaVe();
            dataRow[5] = s.getTrangThai();
            tblModel2.addRow(dataRow);
           
        }
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void tblChuyenXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuyenXeMouseClicked
           try{
            int row = tblChuyenXe.getSelectedRow();
            
            if(row >=0){
                int id = (int) tblChuyenXe.getValueAt(row,0);
                ChuyenXeDao dao = new ChuyenXeDao();
                ChuyenXe cx = dao.finBuyId(id);
                VeXeDao vexedao  = new VeXeDao();
                soluongghe = vexedao.DemSoGhe(cx.getMaChuyen());
                
                
                if( cx != null && soluongghe<=2){                
                    txtNgaydi.setText(cx.getNgayDi().toString());
                    txtGiodi.setText(cx.getGioDi().toString());
                    txtMaChuyen.setText(String.valueOf(cx.getMaChuyen()));                
                    curTime();
                    txtNhanVien.setText(String.valueOf(ShareData.nguoidangnhap.getManv())); 
                    txtThanhTien.setText(String.valueOf(cx.getGiaVe()));
                    soluongghe = vexedao.DemSoGhe(Integer.parseInt(txtMaChuyen.getText().toString()));
                    lblCountGhe.setText(String.valueOf(soluongghe));
                }else if(cx != null && soluongghe > 2){
                    messagedialoghelper.showErorDialog(parentForm, "Chuyến này đã hết vé", "Lỗi");
                }
            }
        } catch (Exception e){
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblChuyenXeMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
       
    }//GEN-LAST:event_btnTimActionPerformed
   
    private void cbxMaTuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMaTuyenItemStateChanged
         try{
            String a = cbxMaTuyen.getSelectedItem().toString();
            TuyenXeDao dao = new TuyenXeDao();
            TuyenXe cx = dao.findBuyId(a);
            
            if( cx!= null)
            {              
                String ab = String.valueOf(cx.getMaTuyen());
                txtMatuyen.setText(ab);
                
            }
            else{
                messagedialoghelper.showMessageDialog(parentForm, "Không tìm thấy chuyến xe","Thông báo");
            }

        } catch (Exception e){
//            e.printStackTrace();
//            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi gì đấy");
        }           
    }//GEN-LAST:event_cbxMaTuyenItemStateChanged
      
    private void btnDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatVeActionPerformed
//        StringBuilder sb = new StringBuilder();
//        DataValidator.validateEmty(txtMatuyen, sb, "Mã chuyến không được để trống");
//        DataValidator.validateEmty(txtGiodi, sb, "Giờ đi không được để trống");
//        DataValidator.validateEmty(txtGiave, sb, "Giá vé không được để trống");
//        DataValidator.validateEmty(txtNgaydi, sb, "Ngày đi không được để trống");
//        if (sb.length()>0){
//            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
//            return;
//        }     
           //ThemKH neu KH chua ton tai
           KhachHangDao khdao =new KhachHangDao();
           String a = txtSdt.getText();
            KhachHang kh = null;
            try {
                kh = khdao.findbySDT(a);
            } catch (Exception ex) {
                Logger.getLogger(DatVePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (kh != null)
            {
                VeXe vx = new VeXe();        
                vx.setMaChuyen(Integer.parseInt(txtMaChuyen.getText()));          
                vx.setMaKH((kh.getMaKH()));
                vx.setMaNV(Integer.parseInt(txtNhanVien.getText()));
                if(soluongghe == 0){
                   vx.setMaSoGhe("1"); 
                }else{
                    masoghe = String.valueOf((soluongghe+1));
                    vx.setMaSoGhe(masoghe);
                }              
                vx.setTongTien((int) Double.parseDouble(txtThanhTien.getText()));
                vx.setThoiGianDat(Date.valueOf((txtNgaydat.getText())));
                VeXeDao dao = new VeXeDao();               
               try {
                   if(dao.Insert(vx)){
                       messagedialoghelper.showMessageDialog(parentForm, "Thêm vé thành công", "Thông báo");
                       ChuyenXeDao chuyenXeDao = new ChuyenXeDao();
                       ChuyenXe cx = chuyenXeDao.finBuyId(vx.getMaChuyen());
                       if(dao.DemSoGhe(vx.getMaChuyen()) > 2){                          
                           cx.setTrangThai("Hết vé");
                           chuyenXeDao.UpdateChuyeXe(cx);
                       }else{
                            cx.setTrangThai("Còn vé");
                            chuyenXeDao.UpdateChuyeXe(cx);
                       }
                       ResetData();
                       loadDataToTable();
                   }else{
                       messagedialoghelper.showConfirmDialog(parentForm, "Vé không được lưu do lỗi", "Cảnh báo");
                   }
               } catch (Exception ex) {
                   Logger.getLogger(DatVePanel.class.getName()).log(Level.SEVERE, null, ex);
               }
            }else{
               //Them KH neu KH la KH moi
                KhachHang khdatve = new KhachHang();
                khdatve.setTenKH(txtHoten.getText());
                khdatve.setSdt(txtSdt.getText());
                khdatve.setNgaySinh(Date.valueOf((txtNgaySinh.getText())));            
               try {
                   khdao.insert(khdatve);
                   VeXe cx = new VeXe();        
                cx.setMaChuyen(Integer.parseInt(txtMaChuyen.getText()));          
                cx.setMaKH((khdatve.getMaKH()));
                cx.setMaNV(Integer.parseInt(txtNhanVien.getText()));
                cx.setMaSoGhe((txtMaGhe.getText()));
                cx.setTongTien((int) Double.parseDouble(txtThanhTien.getText()));
                cx.setThoiGianDat(Date.valueOf((txtNgaydat.getText())));
                
                VeXeDao dao = new VeXeDao();
               try {
                   if(dao.Insert(cx)){
                       messagedialoghelper.showMessageDialog(parentForm, "Thêm vé thành công", "Thông báo");
                       loadDataToTable();
                   }else{
                       messagedialoghelper.showConfirmDialog(parentForm, "Vé không được lưu do lỗi", "Cảnh báo");                               
                   }
               } catch (Exception ex) {
                   Logger.getLogger(DatVePanel.class.getName()).log(Level.SEVERE, null, ex);
               }
                
                
               } catch (Exception ex) {
                   Logger.getLogger(DatVePanel.class.getName()).log(Level.SEVERE, null, ex);
               }
    }//GEN-LAST:event_btnDatVeActionPerformed
 }
    private void txtNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhanVienActionPerformed

    private void txtSdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSdtKeyReleased
        
    }//GEN-LAST:event_txtSdtKeyReleased

    private void txtSdtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSdtCaretUpdate
        KhachHangDao dao = new KhachHangDao();
        String a = txtSdt.getText();
        try {
            KhachHang kh = dao.findbySDT(a);
            if (kh != null)
            {
                txtHoten.setText(kh.getTenKH());
                txtNgaySinh.setText(kh.getNgaySinh().toLocalDate().toString());
                txtMaKh.setText(String.valueOf(kh.getMaKH()));
            }else{
               txtHoten.setText("");
               txtNgaySinh.setText("");
               txtMaKh.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(DatVePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSdtCaretUpdate

    private void txtMatuyenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatuyenKeyReleased
        //        quenry = Integer.parseInt(txtMatuyen.getText().toString());
        //        filter();
    }//GEN-LAST:event_txtMatuyenKeyReleased

    private void txtMatuyenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMatuyenCaretUpdate
        quenry = Integer.parseInt(txtMatuyen.getText());
        filter();
    }//GEN-LAST:event_txtMatuyenCaretUpdate

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        ResetData();
    }//GEN-LAST:event_btnLamMoiActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnDatVe;
      private javax.swing.JButton btnLamMoi;
      private javax.swing.JButton btnTim;
      private javax.swing.JComboBox<String> cbxMaTuyen;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel14;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTextField jTextField1;
      private javax.swing.JLabel lblCountGhe;
      private javax.swing.JTable tblChuyenXe;
      private javax.swing.JTextField txtGiodi;
      private javax.swing.JTextField txtHoten;
      private javax.swing.JTextField txtMaChuyen;
      private javax.swing.JTextField txtMaGhe;
      private javax.swing.JTextField txtMaKh;
      private javax.swing.JTextField txtMatuyen;
      private javax.swing.JTextField txtNgaySinh;
      private javax.swing.JTextField txtNgaydat;
      private javax.swing.JTextField txtNgaydi;
      private javax.swing.JTextField txtNhanVien;
      private javax.swing.JTextField txtSdt;
      private javax.swing.JTextField txtThanhTien;
      // End of variables declaration//GEN-END:variables
   
}
