/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.VeXeDao;
import helper.messagedialoghelper;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.VeXe;

/**
 *
 * @author ASUS
 */
public
        class formthongke extends javax.swing.JFrame {

   private mainform parentform;
    private DefaultTableModel tblmodel;
      public
              formthongke() {
            initComponents();
             inittable();
            LoadDataToTable();
      }
      private void inittable() {
        tblmodel = new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"ma ve","ma chuyen","ma kh","ma nhan vien","ma so ghe","thoi gian dat","tong tien"});
        tblthongke.setModel(tblmodel);
    }
       private void LoadDataToTable() {
        try {
            VeXeDao dao = new VeXeDao();
            List<VeXe> list = dao.findAll();
            tblmodel.setRowCount(0);
            for (VeXe it : list) {
                tblmodel.addRow(new Object[]{
                    it.getMaVe(), it.getMaChuyen(),it.getMaKH(), it.getMaNV(), it.getMaSoGhe(),it.getThoiGianDat(),it.getTongTien()
                });

            }
            tblmodel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentform, e.getMessage(), "loi");
        }
    }
      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jScrollPane1 = new javax.swing.JScrollPane();
            tblthongke = new javax.swing.JTable();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            tblthongke.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                  }
            ));
            jScrollPane1.setViewportView(tblthongke);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(236, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      /**
       * @param args the command line arguments
       */
      public static
              void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(formthongke.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(formthongke.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(formthongke.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(formthongke.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public
                          void run() {
                        new formthongke().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTable tblthongke;
      // End of variables declaration//GEN-END:variables
}
