/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class mainform extends javax.swing.JFrame {

private quanlynhanvienpanel studentpanel;
private QL_ChuyenPanel qlchuyenpanel;
private DatVePanel vePanel;
private quanlytuyenxe qltuyenpanel;
private quanlykhpanel qlkhpanel;
//private vexe vexe;  
    public mainform() {
        initComponents();
        setLocationRelativeTo(null);
       
    }

  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bntdãnguat = new javax.swing.JButton();
        tabquanlysinhvien = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btngioithieu = new javax.swing.JButton();
        tabmainbroad = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuthoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuquanlysinhvien = new javax.swing.JMenuItem();
        jMenuQLChuyen = new javax.swing.JMenuItem();
        jMenuItemQLTuyen = new javax.swing.JMenuItem();
        jMenuItemQLKH = new javax.swing.JMenuItem();
        jMenuDatVe = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bntdãnguat.setText("dăng xuất");
        bntdãnguat.setFocusable(false);
        bntdãnguat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntdãnguat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntdãnguat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdãnguatActionPerformed(evt);
            }
        });
        jToolBar1.add(bntdãnguat);

        tabquanlysinhvien.setText("quản lý nhân viên");
        tabquanlysinhvien.setFocusable(false);
        tabquanlysinhvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabquanlysinhvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tabquanlysinhvien);

        jButton3.setText("help");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        btngioithieu.setText("giới thiệu");
        btngioithieu.setFocusable(false);
        btngioithieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btngioithieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btngioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngioithieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btngioithieu);

        jMenu1.setText("hệ thống");

        jMenuItem1.setText("đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuthoat.setText("thoát");
        menuthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuthoatActionPerformed(evt);
            }
        });
        jMenu1.add(menuthoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("quản lý");

        menuquanlysinhvien.setText("quản lý nhân viên");
        menuquanlysinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuquanlysinhvienActionPerformed(evt);
            }
        });
        jMenu2.add(menuquanlysinhvien);

        jMenuQLChuyen.setText("quản lí chuyến");
        jMenuQLChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQLChuyenActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQLChuyen);

        jMenuItemQLTuyen.setText("quản lí tuyến");
        jMenuItemQLTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQLTuyenActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemQLTuyen);

        jMenuItemQLKH.setText("quản lí khách hàng");
        jMenuItemQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQLKHActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemQLKH);

        jMenuDatVe.setText("đặt vé");
        jMenuDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDatVeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuDatVe);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("trợ giúp");

        jMenuItem4.setText("nội dung");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("giới thiệu");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabmainbroad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabmainbroad, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuthoatActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuthoatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       formlogin form = new formlogin();
      form.setVisible(true);
      this.dispose();
        

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btngioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngioithieuActionPerformed
        AboutUsdialog ab = new AboutUsdialog(this, true);
       ab.setVisible(true);
    }//GEN-LAST:event_btngioithieuActionPerformed

    private void bntdãnguatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdãnguatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntdãnguatActionPerformed

    private void jMenuQLChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQLChuyenActionPerformed

         if (qlchuyenpanel == null) {
            qlchuyenpanel = new QL_ChuyenPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/iconman1.png"));
            tabmainbroad.addTab("quản ly chuyến ", icon, qlchuyenpanel, "Quan Ly Chuyen");
        }

        tabmainbroad.setSelectedComponent(qlchuyenpanel);
    }//GEN-LAST:event_jMenuQLChuyenActionPerformed

    private void menuquanlysinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuquanlysinhvienActionPerformed
        if (studentpanel == null) {
            studentpanel = new quanlynhanvienpanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/iconman1.png"));
            tabmainbroad.addTab("quản ly sinh vien ", icon, studentpanel, "quan ly sinh vien");
        }

        tabmainbroad.setSelectedComponent(studentpanel);
    }//GEN-LAST:event_menuquanlysinhvienActionPerformed

    private void jMenuItemQLTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQLTuyenActionPerformed
        if (qltuyenpanel == null) {
            qltuyenpanel = new quanlytuyenxe();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/iconman1.png"));
            tabmainbroad.addTab("quản lý tuyến ", icon, qltuyenpanel, "Quan Ly Tuyen");
        }

        tabmainbroad.setSelectedComponent(qltuyenpanel);
    }//GEN-LAST:event_jMenuItemQLTuyenActionPerformed

    private void jMenuItemQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQLKHActionPerformed
       if (qlkhpanel == null) {
            qlkhpanel = new quanlykhpanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/iconman1.png"));
            tabmainbroad.addTab("quản lý khách hàng ", icon, qlkhpanel, "Quan Ly Khach Hang");
        }

        tabmainbroad.setSelectedComponent(qltuyenpanel);
    }//GEN-LAST:event_jMenuItemQLKHActionPerformed

    private void jMenuDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDatVeActionPerformed
       if (vePanel == null) {
            vePanel = new DatVePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/iconman1.png"));
            tabmainbroad.addTab("Đặt Vé ", icon, vePanel, "Dat Ve");
        }

        tabmainbroad.setSelectedComponent(vePanel);
    }//GEN-LAST:event_jMenuDatVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */       
          java.awt.EventQueue.invokeLater(() -> {
            new formlogin().setVisible(true);
        });
       
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntdãnguat;
    private javax.swing.JButton btngioithieu;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDatVe;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemQLKH;
    private javax.swing.JMenuItem jMenuItemQLTuyen;
    private javax.swing.JMenuItem jMenuQLChuyen;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuquanlysinhvien;
    private javax.swing.JMenuItem menuthoat;
    private javax.swing.JTabbedPane tabmainbroad;
    private javax.swing.JButton tabquanlysinhvien;
    // End of variables declaration//GEN-END:variables
}
