/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.*;
import helper.*;
import model.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class QL_ChuyenPanel extends javax.swing.JPanel {

    /**
     * Creates new form QL_ChuyenPanel
     */
    private mainform parentForm;
    private DefaultTableModel tblModel;
    
    public QL_ChuyenPanel() {
        initComponents();
        
        initTable();
        
        loadDataToTable();
        LoadTuyenToCombobox();    
    }
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Chuyến", "Mã Tuyến","Ngày đi", "Giờ đi", "Giá vé"});
        tblChuyenXe.setModel(tblModel);
    }
    public void loadDataToTable(){
        try{
            ChuyenXeDao dao = new ChuyenXeDao();
            List<ChuyenXe> list = dao.findAll();
            tblModel.setRowCount(0);
            for(ChuyenXe it : list){
                tblModel.addRow(new Object[]{
                it.getMaChuyen(), it.getMaTuyen(), it.getNgayDi(), it.getGioDi(), it.getGiaVe()
            });
            }
            tblModel.fireTableDataChanged();
        } catch(Exception e)
        {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Loi");
        }
    }
    
     public void LoadTuyenToCombobox(){
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost;databaseName=QLVEXE;user=sa;password=123";
        Connection con = DriverManager.getConnection(connectionUrl);
        String sql ="select MaTuyen,TenTuyen from TuyenXe";
        Statement st =con.createStatement();
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            cbxTuyen.removeAllItems();
            while (rs.next()){
                cbxTuyen.addItem(rs.getString("TenTuyen"));
                cbxTuyen.setSelectedItem("");
            }
            rs.close();
            pstmt.close();
            con.close();
        }catch(Exception e)
        {
            e.getStackTrace();
        }
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cbxTuyen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChuyenXe = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        bntXoa = new javax.swing.JButton();
        btnTaomoi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtMatuyen = new javax.swing.JTextField();
        txtMachuyen = new javax.swing.JTextField();
        txtGiodi = new javax.swing.JTextField();
        txtGiave = new javax.swing.JTextField();
        txtNgaydi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ CHUYẾN");

        jLabel6.setText("Tuyến đường");

        cbxTuyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTuyenItemStateChanged(evt);
            }
        });

        tblChuyenXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChuyenXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuyenXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChuyenXe);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        bntXoa.setText("Xóa");
        bntXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaActionPerformed(evt);
            }
        });

        btnTaomoi.setText("Tạo mới");
        btnTaomoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomoiActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtMatuyen.setEnabled(false);

        txtMachuyen.setEnabled(false);

        txtGiodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiodiActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã tuyến");

        jLabel2.setText("Mã chuyến");

        jLabel3.setText("Giờ");

        jLabel4.setText("Giá vé");

        jLabel5.setText("Ngày đi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 57, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgaydi, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtGiave, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiodi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMachuyen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatuyen))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtMatuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMachuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaydi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnTimKiem)
                                .addGap(18, 18, 18)
                                .addComponent(btnTaomoi)
                                .addGap(25, 25, 25)
                                .addComponent(btnThem)
                                .addGap(30, 30, 30)
                                .addComponent(btnSua)
                                .addGap(35, 35, 35)
                                .addComponent(bntXoa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cbxTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThem)
                                .addComponent(btnSua)
                                .addComponent(bntXoa)
                                .addComponent(btnTaomoi))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTimKiem)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiodiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       StringBuilder sb = new StringBuilder();
        datavailditor.validataEmty(txtMatuyen, sb, "Mã tuyến không được để trống");
        datavailditor.validataEmty(txtGiodi, sb, "Giờ đi không được để trống");
        datavailditor.validataEmty(txtGiave, sb, "Giá vé không được để trống");
        datavailditor.validataEmty(txtNgaydi, sb, "Ngày đi không được để trống");
        if (sb.length()>0){
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try{
           ChuyenXe cx = new ChuyenXe();        
           cx.setMaTuyen(Integer.parseInt(txtMatuyen.getText()));          
           cx.setGioDi(Time.valueOf(txtGiodi.getText()));
           cx.setGiaVe(Double.parseDouble(txtGiave.getText()));
           cx.setNgayDi(Date.valueOf((txtNgaydi.getText())));
           cx.setTrangThai("Còn vé"); 
           
           ChuyenXeDao dao = new ChuyenXeDao();
           if(dao.insert(cx)){
               messagedialoghelper.showMessageDialog(parentForm, "Thêm chuyến thành công", "Thông báo");
               loadDataToTable();
           }else{
               messagedialoghelper.showConfirmDialog(parentForm, "Chuyến không được lưu do lỗi", "Cảnh báo");
           }
       } catch (Exception e){
           e.printStackTrace();
           messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi");
       }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomoiActionPerformed
        txtMachuyen.setText("");
        txtGiodi.setText("");
        txtNgaydi.setText("");
        txtGiave.setText("");
    }//GEN-LAST:event_btnTaomoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        StringBuilder sb = new StringBuilder();
        datavailditor.validataEmty(txtMatuyen, sb, "Mã tuyến không được để trống");
        datavailditor.validataEmty(txtGiodi, sb, "Giờ đi không được để trống");
        datavailditor.validataEmty(txtGiave, sb, "Giá vé không được để trống");
        datavailditor.validataEmty(txtNgaydi, sb, "Ngày đi không được để trống");
           if (sb.length()>0){
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(messagedialoghelper.showConfirmDialog(parentForm, 
                "Bạn có muốn sửa chuyến xe không","Hỏi") == JOptionPane.NO_OPTION ){
                return;
        }
        try{
           ChuyenXe cx = new ChuyenXe(); 
           cx.setMaChuyen(Integer.parseInt(txtMachuyen.getText()));  
           cx.setMaTuyen(Integer.parseInt(txtMatuyen.getText()));          
           cx.setGioDi(Time.valueOf(txtGiodi.getText()));
           cx.setGiaVe(Double.parseDouble(txtGiave.getText()));
           cx.setNgayDi(Date.valueOf((txtNgaydi.getText())));          
           ChuyenXeDao dao = new ChuyenXeDao();
           if(dao.UpdateChuyeXe(cx)){
               messagedialoghelper.showMessageDialog(parentForm, "Chuyến xe đã được cập nhật", "Thông báo");
               loadDataToTable();
           }else{
               messagedialoghelper.showConfirmDialog(parentForm, "Chuyến không được cập nhật do lỗi", "Cảnh báo");
           }
       } catch (Exception e){
           e.printStackTrace();
           messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi");
       }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void bntXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaActionPerformed
        StringBuilder sb = new StringBuilder();       
        datavailditor.validataEmty(txtMachuyen, sb, "Mã chuyến không được để trống");
           if (sb.length()>0){
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(messagedialoghelper.showConfirmDialog(parentForm, 
            "Bạn có muốn xóa chuyến xe không","Hỏi") == JOptionPane.NO_OPTION ){
            return;
        }
        try{     
           ChuyenXeDao dao = new ChuyenXeDao();
           if(dao.DeleteChuyeXe(Integer.parseInt(txtMachuyen.getText()))){
               messagedialoghelper.showMessageDialog(parentForm, "Chuyến xe đã được xóa", "Thông báo");
               loadDataToTable();
               btnTaomoiActionPerformed(evt);
           }else{
               messagedialoghelper.showConfirmDialog(parentForm, "Chuyến không được xóa do lỗi", "Cảnh báo");
           }
       } catch (Exception e){
           e.printStackTrace();
           messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi");
       }
    }//GEN-LAST:event_bntXoaActionPerformed

    private void tblChuyenXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuyenXeMouseClicked
        try{
            int row = tblChuyenXe.getSelectedRow();
            
            if(row >=0){
                int id = (int) tblChuyenXe.getValueAt(row,0);
                ChuyenXeDao dao = new ChuyenXeDao();
                ChuyenXe cx = dao.finBuyId(id);
                
                if( cx != null){
                    txtMachuyen.setText(String.valueOf(cx.getMaChuyen()));
                    txtMatuyen.setText(String.valueOf(cx.getMaTuyen()));
                    txtGiodi.setText(cx.getGioDi().toLocalTime().toString());
                    txtGiave.setText(cx.getGiaVe().toString());
                    txtNgaydi.setText(cx.getNgayDi().toString());
                }
            }
        } catch (Exception e){
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblChuyenXeMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try{
            ChuyenXeDao dao = new ChuyenXeDao();
            ChuyenXe cx = dao.finBuyId(Integer.parseInt(txtTimKiem.getText()));
            
            if( cx!= null)
            {
                txtMachuyen.setText(String.valueOf(cx.getMaChuyen()));
                txtMatuyen.setText(String.valueOf(cx.getMaTuyen()));
                txtGiave.setText(cx.getGiaVe().toString());
                txtGiodi.setText(cx.getGioDi().toLocalTime().toString());
                txtNgaydi.setText(cx.getNgayDi().toString());
            }else{
                messagedialoghelper.showMessageDialog(parentForm, "Không tìm thấy chuyến xe","Thông báo");
            }
        } catch (Exception e){
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed
   

    private void cbxTuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTuyenItemStateChanged
        try{
            String a = cbxTuyen.getSelectedItem().toString();
            TuyenXeDao dao = new TuyenXeDao();
            TuyenXe cx = dao.findBuyId(a);
            
            if( cx!= null)
            {              
                txtMatuyen.setText(String.valueOf(cx.getMaTuyen()));  
                
            }else{
                messagedialoghelper.showMessageDialog(parentForm, "Không tìm thấy chuyến xe","Thông báo");
            }

        } catch (Exception e){
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Lỗi gì đấy");
        }
    }//GEN-LAST:event_cbxTuyenItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntXoa;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaomoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxTuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblChuyenXe;
    private javax.swing.JTextField txtGiave;
    private javax.swing.JTextField txtGiodi;
    private javax.swing.JTextField txtMachuyen;
    private javax.swing.JTextField txtMatuyen;
    private javax.swing.JTextField txtNgaydi;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
