/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import dao.TuyenXe1Dao;
import dao.TuyenXeDao;
import helper.datavailditor;
import helper.databasehelper;
import helper.messagedialoghelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.TuyenXe;

/**
 *
 * @author ASUS
 */
public class quanlytuyenxe extends javax.swing.JPanel {
     private  mainform parentForm;
     private DefaultTableModel tblModel;
    /**
     *
     */
    public quanlytuyenxe() {
        initComponents();
        initComboBox1();
        initTableTX();
       loadDataToTableTX();
    }
    
   private void initComboBox1(){
       String sql =" select TenTuyen from TuyenXe";
       try {
           
           Connection con = databasehelper.openConnection();
           PreparedStatement pstmt = con.prepareStatement(sql);
           ResultSet rs = pstmt.executeQuery();
           cbbTenTuyen.removeAllItems();     
           while (rs.next()) {               
               cbbTenTuyen.addItem(rs.getString("TenTuyen"));
           }
           rs.close();
           pstmt.close();
           con.close();
           
       } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Lỗi 3");
        }
  
    }
   
    private void initTableTX(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Tuyến","Tên Tuyến"});
        tblqltuyen.setModel(tblModel);  
    }
    
    private void loadDataToTableTX(){
        try {
                TuyenXe1Dao dao = new TuyenXe1Dao();
               List<TuyenXe> list = dao.findAll();
                tblModel.setRowCount(0);
                for (TuyenXe it : list) { 
                    tblModel.addRow(new Object[]{
                        it.getMaTuyen(), it.getTenTuyen()
                    });
                }
                tblModel.fireTableDataChanged();               
        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "lỗi");
        }
  
    }
    
    public boolean isStringInt(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaTuyen = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblqltuyen = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cbbTenTuyen = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        jLabel1.setText("Quản Lý Tuyến Xe");

        jLabel2.setText("Mã Tuyến");

        jLabel3.setText("Tên Tuyến");

        txtMaTuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaTuyen.setEnabled(false);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblqltuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblqltuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblqltuyenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblqltuyen);

        cbbTenTuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbTenTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTenTuyenActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbTenTuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaTuyen))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(btnThem)
                            .addComponent(btnLamMoi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTimKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnThoat)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbbTenTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTimKiem))
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLamMoi)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();
//        datavailditor.validataEmty(txtMaTuyen, sb, "Mã tuyến không được để trống");

        if (sb.length() > 0) {
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "lỗi 1");
            return;
        }

        try {
            TuyenXe tx = new TuyenXe();
//            tx.setMaTuyen(txtMaTuyen.getText());
            tx.setTenTuyen(cbbTenTuyen.getSelectedItem().toString());
            

            TuyenXe1Dao dao = new TuyenXe1Dao();
            if (dao.insert(tx)) {
                messagedialoghelper.showMessageDialog(parentForm, "Thêm tuyến thành công", "Thông báo");
            loadDataToTableTX();
            } else {
                messagedialoghelper.showConfirmDialog(parentForm, "tuyến không được Thêm do lỗi", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "Lỗi them");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaTuyen.setText("");
        cbbTenTuyen.setSelectedIndex(0);
       
        loadDataToTableTX();
     
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cbbTenTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTenTuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTenTuyenActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        StringBuilder sb = new StringBuilder();
//        datavailditor.validataEmty(txtMaTuyen, sb, "Mã Tuyen không được để trống");
        
        if (sb.length()>0) {
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "lỗi 1");
            return;
        }
        
        if (messagedialoghelper.showConfirmDialog(parentForm, "Bạn có muốn Sửa Tuyen không", "Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try {
            TuyenXe tx = new TuyenXe();
            tx.setMaTuyen(Integer.valueOf(txtMaTuyen.getText()));
            tx.setTenTuyen(cbbTenTuyen.getSelectedItem().toString());
            
                    
            TuyenXe1Dao dao =new TuyenXe1Dao();
            if (dao.update(tx)) {
            messagedialoghelper.showMessageDialog(parentForm, "Sửa tuyen thành công", "Thông báo");
            loadDataToTableTX();
            }else{
            messagedialoghelper.showConfirmDialog(parentForm, "tuyen không được sửa do lỗi", "Cảnh báo");
            }
            } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi 2");
            }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();
//        datavailditor.validataEmty(txtMaTuyen, sb, "Mã Tuyến không được để trống");
      
        if (sb.length()>0) {
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "lỗi 1");
            return;
        }
        
        if (messagedialoghelper.showConfirmDialog(parentForm, "Bạn có muốn xóa Tuyến không", "Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try {
         
                    
            TuyenXe1Dao dao =new TuyenXe1Dao();
            if (dao.Delete(Integer.valueOf(txtMaTuyen.getText()))) {
            messagedialoghelper.showMessageDialog(parentForm, "Xóa tuyến thành công", "Thông báo");
                btnLamMoiActionPerformed(evt);
                loadDataToTableTX();
            }else{
            messagedialoghelper.showConfirmDialog(parentForm, "tuyến không được xóa do lỗi", "Cảnh báo");
            }
            } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi 2");
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
             if (txtTimKiem.getText().equals("")) {
            messagedialoghelper.showMessageDialog(parentForm,"Nhập ký tự tìm kiếm", "thông báo");
            return;
        }         
          try {
            if (!isStringInt(txtTimKiem.getText())) {

                TuyenXe1Dao dao = new TuyenXe1Dao();
                List<TuyenXe> listname = dao.findTableName2(txtTimKiem.getText());
                tblModel.setRowCount(0);
                for (TuyenXe it : listname) {
                    tblModel.addRow(new Object[]{
                        it.getMaTuyen(), it.getTenTuyen()
                    });
                }
                tblModel.fireTableDataChanged();

            } else {
                TuyenXe1Dao dao = new TuyenXe1Dao();
                List<TuyenXe> list = dao.findTable(Integer.valueOf(txtTimKiem.getText()));
                tblModel.setRowCount(0);
                for (TuyenXe it : list) {
                    tblModel.addRow(new Object[]{
                        it.getMaTuyen(), it.getTenTuyen()
                    });
                }
                tblModel.fireTableDataChanged();
            }

        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "lỗi");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblqltuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblqltuyenMouseClicked
         try {
                int row = tblqltuyen.getSelectedRow();
                
                if(row >= 0){
                    int id =  (int) tblqltuyen.getValueAt(row, 0);
                    TuyenXe1Dao dao = new TuyenXe1Dao();
                    TuyenXe tx = dao.findbyId(id);
                    
                    if (tx!=null) {
                        txtMaTuyen.setText(String.valueOf(tx.getMaTuyen()));
                        cbbTenTuyen.setSelectedItem(tx.getTenTuyen());
                        
                       

                    }
                }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblqltuyenMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTenTuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblqltuyen;
    private javax.swing.JTextField txtMaTuyen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
