/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.*;
import helper.datavailditor;
import helper.messagedialoghelper;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import java.util.List;
import helper.databasehelper;


/**
 *
 * @author ASUS
 */
public class quanlykhpanel extends javax.swing.JPanel {
    private  mainform parentForm;
    private DefaultTableModel tblModel;
    /**
   
     */
    public quanlykhpanel() {
        initComponents();
        
        initTable();
        
        loadDataToTable();
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Kh","Tên Kh","SDT","Ngày Sinh"});
        tblKh.setModel(tblModel);  
    }
    
    private void loadDataToTable(){
        try {
                KhachHangDao dao = new KhachHangDao();
               List<KhachHang> list = dao.findAll();
                tblModel.setRowCount(0);
                for (KhachHang it : list) { 
                    tblModel.addRow(new Object[]{
                        it.getMaKH(), it.getTenKH(), it.getSdt(), it.getNgaySinh()
                    });
                }
                tblModel.fireTableDataChanged();               
        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "lỗi");
        }
    }
    
    public boolean isStringInt(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKh = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtTimKiem = new javax.swing.JTextField();

        jLabel1.setText("Quản lý Khách Hàng");

        jLabel2.setText("Mã KH");

        jLabel3.setText("Tên KH");

        jLabel4.setText("SDT");

        jLabel5.setText("Ngày Sinh");

        txtMaKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaKH.setEnabled(false);

        tblKh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKh);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenKH)
                            .addComponent(txtSDT)
                            .addComponent(txtNgaySinh)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTimKiem)
                                .addGap(28, 28, 28)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaKH.setText("");
        txtTenKH.setText("");
        txtSDT.setText("");
        txtNgaySinh.setText("");
        loadDataToTable();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();
//        datavailditor.validataEmty(txtMaKH, sb, "Mã KH không được để trống");
        datavailditor.validataEmty(txtTenKH, sb, "tên KH không được để trống");
        datavailditor.validataEmty(txtSDT, sb, "SDT KH không được để trống");
        datavailditor.validataEmty(txtNgaySinh, sb, "ngày sinh KH không được để trống");
        if (sb.length()>0) {
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "lỗi 1");
            return;
        }
        
      
         try {
            KhachHang kh = new KhachHang();
//            kh.setMaKH(Integer.valueOf(txtMaKH.getText()));
            kh.setTenKH(txtTenKH.getText());
            kh.setSdt(txtSDT.getText());
            kh.setNgaySinh(Date.valueOf((txtNgaySinh.getText())));
                    
            KhachHangDao dao =new KhachHangDao();
            if (dao.insert(kh)) {
            messagedialoghelper.showMessageDialog(parentForm, "Thêm Kh thành công", "Thông báo");
            loadDataToTable();
            }else{
            messagedialoghelper.showConfirmDialog(parentForm, "Kh không được Thêm do lỗi", "Cảnh báo");
            }
            } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi 2");
            }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         StringBuilder sb = new StringBuilder();
//        datavailditor.validataEmty(txtMaKH, sb, "Mã KH không được để trống");
        datavailditor.validataEmty(txtTenKH, sb, "tên KH không được để trống");
        datavailditor.validataEmty(txtSDT, sb, "SDT KH không được để trống");
        datavailditor.validataEmty(txtNgaySinh, sb, "ngày sinh KH không được để trống");
        if (sb.length()>0) {
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "lỗi 1");
            return;
        }
        
        if (messagedialoghelper.showConfirmDialog(parentForm, "Bạn có muốn Sửa KH không", "Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try {
            KhachHang kh = new KhachHang();
            kh.setMaKH(Integer.valueOf(txtMaKH.getText()));
            kh.setTenKH(txtTenKH.getText());
            kh.setSdt(txtSDT.getText());
            kh.setNgaySinh(Date.valueOf((txtNgaySinh.getText())));
                    
            KhachHangDao dao =new KhachHangDao();
            if (dao.update(kh)) {
            messagedialoghelper.showMessageDialog(parentForm, "Sửa Kh thành công", "Thông báo");
            loadDataToTable();
            }else{
            messagedialoghelper.showConfirmDialog(parentForm, "Kh không được sửa do lỗi", "Cảnh báo");
            }
            } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi 2");
            }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       StringBuilder sb = new StringBuilder();
//        datavailditor.validataEmty(txtMaKH, sb, "Mã KH không được để trống");
      
        if (sb.length()>0) {
            messagedialoghelper.showErorDialog(parentForm, sb.toString(), "lỗi 1");
            return;
        }
        
        if (messagedialoghelper.showConfirmDialog(parentForm, "Bạn có muốn xóa KH không", "Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try {
         
                    
            KhachHangDao dao =new KhachHangDao();
            if (dao.Delete(Integer.valueOf(txtMaKH.getText()))) {
            messagedialoghelper.showMessageDialog(parentForm, "Xóa Kh thành công", "Thông báo");
                btnLamMoiActionPerformed(evt);
                loadDataToTable();
            }else{
            messagedialoghelper.showConfirmDialog(parentForm, "Kh không được xóa do lỗi", "Cảnh báo");
            }
            } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog((parentForm), e.getMessage(), "Lỗi 2");
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblKhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhMouseClicked
        try {
                int row = tblKh.getSelectedRow();
                
                if(row >= 0){
                    int id =  (int) tblKh.getValueAt(row, 0);
                    KhachHangDao dao = new KhachHangDao();
                    KhachHang kh = dao.findbyId(id);
                    
                    if (kh!=null) {
                        txtMaKH.setText(String.valueOf(kh.getMaKH()));
                        txtTenKH.setText(kh.getTenKH());
                        txtSDT.setText(kh.getSdt());
                        txtNgaySinh.setText(kh.getNgaySinh().toLocalDate().toString());

                    }
                }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblKhMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (txtTimKiem.getText().equals("")) {
            messagedialoghelper.showMessageDialog(parentForm, "Nhập ký tự tìm kiếm", "thông báo");
            return;
        }
        try {
            KhachHangDao dao = new KhachHangDao();
            if (!isStringInt(txtTimKiem.getText())) {
                List<KhachHang> listname = dao.findTableName(txtTimKiem.getText());

                tblModel.setRowCount(0);
                for (KhachHang it : listname) {
                    tblModel.addRow(new Object[]{
                        it.getMaKH(), it.getTenKH(), it.getSdt(), it.getNgaySinh()
                    });
                }
                tblModel.fireTableDataChanged();

            } else {
                List<KhachHang> list = dao.findTable(Integer.valueOf(txtTimKiem.getText()));
                tblModel.setRowCount(0);
                for (KhachHang it : list) {
                    tblModel.addRow(new Object[]{
                        it.getMaKH(), it.getTenKH(), it.getSdt(), it.getNgaySinh()
                    });
                }
                tblModel.fireTableDataChanged();
            }

        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErorDialog(parentForm, e.getMessage(), "lỗi");
        } 
       
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblKh;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
